client/Dockerfile, docker-compose.yml
Added client to the docker-compose
=> Added Client part to docker-compose

client/src/app/components/mission-single/mission-single.component.css, client/src/app/components/mission-single/mission-single.component.html
- mission-single : restructure
- mission-single : overlapping vulns in hosts list
=> CSS_mission-single

README.md, api/src/Entity/Mission.php, client/src/app/components/mission-create/mission-create.component.html, client/src/app/components/mission-create/mission-create.component.ts, client/src/app/components/mission-edit/mission-edit.component.ts, client/src/app/components/mission-single/mission-single.component.html, client/src/app/components/missions/missionsList.component.ts, client/src/app/components/vulns-create/vulns-create.component.ts, docker-compose.yml
done #24  and force user to set url instead of string
=> add bitwarden 

api/src/DataFixtures/MissionFixtures.php, api/src/Entity/Mission.php, client/src/app/components/mission-edit/mission-edit.component.html, client/src/app/components/mission-edit/mission-edit.component.ts, client/src/app/components/mission-single/mission-single.component.html
=> [Fix] - Change Endate To endate

api/config/packages/api_platform.yaml, api/src/Entity/Client.php, api/src/Entity/Host.php, api/src/Entity/Impact.php, api/src/Entity/Mission.php, api/src/Entity/User.php, api/src/Entity/Vuln.php, api/src/Filter/MissionTypeFilter.php, api/src/Traits/TypeTrait.php, client/src/app/app.component.ts, client/src/app/app.module.ts, client/src/app/components/add-vulns-to-host-external/add-vulns-to-host-external.component.ts, client/src/app/components/clients/clientsList.component.ts, client/src/app/components/conclusion/conclusion.component.ts, client/src/app/components/generic/list/generic-list.component.html, client/src/app/components/generic/list/generic-list.component.ts, client/src/app/components/hosts/hostsList.component.ts, client/src/app/components/mission-create/mission-create.component.ts, client/src/app/components/mission-edit/mission-edit.component.ts, client/src/app/components/mission-single/mission-single.component.html, client/src/app/components/missions/missionsList.component.ts, client/src/app/components/side-bar/side-bar.component.html, client/src/app/components/side-bar/side-bar.component.scss, client/src/app/components/users/usersList.component.ts, client/src/app/components/vulns-create/vulns-create.component.ts, client/src/app/services/abstract.ts, client/src/app/services/filter.service.ts, client/src/app/services/theme.service.ts, client/src/app/services/vulns.service.ts, client/src/styles.scss
=> [FEAT] Issues 34 & 37 - Add search bars and pagination on generic list

client/src/app/components/add-vulns-to-host-external/add-vulns-to-host-external.component.html, client/src/app/components/add-vulns-to-host-external/add-vulns-to-host-external.component.scss
=> [CSS] -  Better form to add vuln on host

client/src/app/components/mission-single/mission-single.component.html
=> [Display] - Display filename of uploaded file

client/src/app/app.module.ts, client/src/app/components/mission-my/mission-my.component.html, client/src/app/components/mission-my/mission-my.component.ts
=> [Display] - Add mission count to dashboard

api/src/Entity/Host.php
Blocks [https://github.com/CMEPW/smersh-cli/pull/28](https://github.com/CMEPW/smersh-cli/pull/28)
=> [Unsed] - Delete Group in Host entity

client/src/app/model/Client.ts
firstname and lastname are now displayed into client view  and mission view
=> [FIX] - Display Client informations

api/src/DataFixtures/MissionFixtures.php, api/src/DataFixtures/UserFixtures.php, api/src/Entity/User.php, client/src/app/components/mission-single/mission-single.component.html, client/src/app/components/user-create/user-create.component.html, client/src/app/components/user-create/user-create.component.scss, client/src/app/components/user-create/user-create.component.ts, client/src/app/components/user-edit/user-edit.component.html, client/src/app/components/user-edit/user-edit.component.ts, client/src/app/model/User.ts
User now have : 
mail, phone,city, trigram
=> [Feat] - Add field for user

README.md, client/src/assets/i18n/ar.json
I saw that some translations were not good, so here are the updates
=> [FIX] - Arab words

api/config/packages/api_platform.yaml, api/src/DataFixtures/MissionFixtures.php, client/src/environments/environment.ts
=> [Update] - Vulns 

api/config/packages/api_platform.yaml, client/Dockerfile, client/src/environments/environment.ts
=> [UPDATE] - Version to 1.1.1

api/config/services.yaml, api/src/Listener/UserCreateListener.php, client/src/environments/environment.ts, docker-compose.yml
When you create new account, user gna have codimd account with same creds #33
=> [Feat] - CodiMD account attach to user

README.md
| Branch?       | 
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | no one, only update readme
=> [README] - Add Badge for Black hat EUROPE 2021

client/src/app/services/locale.service.ts
| Branch?       | 
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       |
=> [Fix] - Media + lang

api/config/packages/api_platform.yaml, client/Dockerfile, client/src/environments/environment.ts
| Branch?      master
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
Just upgrade version for release
=> [Update] - version for release 1.1.3

.github/SECURITY.md
| Branch?       | 
| Bug fix?      | no
| New feature?  | no
| Deprecations? |no
| Tickets       | Fix #150
=> add security readme

client/cypress/support/commands/index.js, client/package-lock.json, client/package.json, client/src/app/components/mission-single/mission-single.component.html, client/src/app/components/mission-single/mission-single.component.ts
| Branch?       | feat-issue-68-add-copy-to-clipboard-FQDN-in-mission-view
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #...
=> feat-issue-68: add copy to clipboard FQDN in mission view
